linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  disable:
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gocyclo
    - revive

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
      - (net/http.ResponseWriter).Write
      - (*github.com/streadway/amqp.Channel).Close
      - (*github.com/streadway/amqp.Connection).Close
      - (github.com/spf13/viper.Viper).BindEnv
      - os.RemoveAll
      - os.MkdirAll
      - os.WriteFile
      - os.Chtimes

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-rules:
    # Ignore errcheck in test files
    - path: _test\.go
      linters:
        - errcheck
    # Ignore Jaeger deprecation warning
    - linters:
        - staticcheck
      text: "SA1019.*jaeger"
    # Ignore empty branch in defer
    - linters:
        - staticcheck  
      text: "SA9003"

run:
  timeout: 5m
  tests: true
